#
# Copyright (c) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Pod
metadata:
  name: security-context-test
spec:
  terminationGracePeriodSeconds: 0
  runtimeClassName: kata
  securityContext:
    runAsUser: 1000
  containers:
  - name: sec-text
    image: docker.io/library/busybox:latest
    command: ["tail", "-f", "/dev/null"]
